### ISSUE TITLE
Bug in deriving scores with vectors that have missing metrics

### ISSUE THREAD

**Issue by nickleali** [akshatvaid/cvss-v4-node-api#2]
As mentioned in email, the API version returns a result even if there are missing vectors. See the following results that return a valid score but are missing metrics -- 

Missing metrics, vuln and others

Missing vuln
CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:L/VI:H/VA:N/SI:H/SA:L

CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:N/VI:N/VA:N/SC:N/SI:L/SA:N

CVSS:4.0/AV:A/AC:L/AT:N/PR:H/UI:A/VC:L/VI:H/VA:L/SI:L/SA:N

CVSS:4.0/AV:L/AC:H/AT:P/PR:H/UI:P/VC:L/VI:L/VA:H/SI:L/SA:H

CVSS:4.0/AV:A/AC:L/AT:N/PR:H/UI:P/VC:L/VI:H/VA:L/SC:H/SA:L/E:A

Missing AC
CVSS:4.0/AV:A/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:H/SI:L/SA:L/CR:H/IR:H/AR:H/MAV:P/MAC:H/MAT:N/MPR:X/MUI:N/MVC:H/MVI:X/MVA:H/MSC:L/MSI:S/MSA:S

**Comment by akshatvaid** [comment]
$ curl "http://10.85.234.18:22177/cvss?q=CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:N/VC:N/VI:N/VA:L/SI:N/SA:H"
{"vector":"CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:N/VC:N/VI:N/VA:L/SI:N/SA:H",
"score":"error",
"severity":"error",
"error":"Invalid vector, missing mandatory metrics: SC"}
