### ISSUE TITLE
Enhancement -- include vector string with negative or invalid string

### ISSUE THREAD

**Issue by nickleali** [akshatvaid/cvss-v4-node-api#3]
Consider for consistency returning the invalid vector string as part of the return from the API, similar to a valid score, but a null result in the score and severity string.

**Comment by akshatvaid** [comment]
Would something like below work? 
API will add an "error" key when incorrect vectors are supplied.

{"vector":"CVSS:/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N",
 "score":"error",
 "severity":"error",
 "error":"Error invalid vector, incorrect CVSS v4.0 prefix"}

**Comment by nickleali** [comment]
That would be perfect, anything informative that returns the originating bad vector and a message confirming that it's invalid, in JSON format.

**Comment by akshatvaid** [comment]
$ curl "http://10.85.234.18:22177/cvss?q=CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:N/VC:N/VI:N/VA:L/SI:N/SA:H"
{"vector":"CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:N/VC:N/VI:N/VA:L/SI:N/SA:H",
 "score":"error",
 "severity":"error",
 "error":"Invalid vector, missing mandatory metrics: SC"}
