### ISSUE TITLE
Possible rounding error returning incorrect results

### ISSUE THREAD

**Issue by nickleali** [akshatvaid/cvss-v4-node-api#8]
As I mentioned, looking at the comparison testing, there might be a rounding error present. Attached some of the vector strings that returned different results.

[boundary_cases.txt](https://github.com/user-attachments/files/16036433/boundary_cases.txt)

A sample -- 

base vectors	python	API
CVSS:4.0/AV:N/AC:H/AT:N/PR:L/UI:P/VC:L/VI:L/VA:L/SC:H/SI:H/SA:N	5	5.1
CVSS:4.0/AV:A/AC:H/AT:P/PR:H/UI:N/VC:L/VI:H/VA:H/SC:N/SI:L/SA:N	5.8	5.9
CVSS:4.0/AV:L/AC:H/AT:N/PR:N/UI:P/VC:L/VI:H/VA:H/SC:N/SI:L/SA:L	5.8	5.9
CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:A/VC:N/VI:N/VA:L/SC:H/SI:H/SA:N	5	5.1
CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:N/VC:N/VI:N/VA:N/SC:L/SI:L/SA:H	5	5.1
CVSS:4.0/AV:L/AC:H/AT:N/PR:N/UI:P/VC:N/VI:H/VA:H/SC:N/SI:N/SA:L/E:U	1.9	2
CVSS:4.0/AV:N/AC:H/AT:P/PR:L/UI:A/VC:L/VI:H/VA:H/SC:L/SI:N/SA:N/E:X	5.8	5.9
CVSS:4.0/AV:A/AC:H/AT:P/PR:N/UI:A/VC:N/VI:L/VA:L/SC:N/SI:N/SA:L/E:U	0.3	0.4
CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:P/VC:N/VI:N/VA:L/SC:H/SI:H/SA:N/E:A	5	5.1
CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:N/VC:H/VI:N/VA:N/SC:N/SI:L/SA:L/E:U	1.6	1.7
CVSS:4.0/AV:A/AC:L/AT:N/PR:L/UI:P/VC:N/VI:H/VA:N/SC:N/SI:L/SA:N/E:X/CR:H/IR:L/AR:M/MAV:A/MAC:X/MAT:P/MPR:N/MUI:X/MVC:N/MVI:L/MVA:X/MSC:L/MSI:L/MSA:H	5	5.1
CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:H/VA:L/SC:H/SI:H/SA:L/E:P/CR:L/IR:X/AR:X/MAV:X/MAC:H/MAT:X/MPR:H/MUI:A/MVC:X/MVI:X/MVA:L/MSC:N/MSI:L/MSA:N	4.3	4.4
CVSS:4.0/AV:P/AC:L/AT:N/PR:N/UI:A/VC:N/VI:H/VA:N/SC:L/SI:H/SA:L/E:P/CR:X/IR:L/AR:X/MAV:X/MAC:H/MAT:P/MPR:H/MUI:P/MVC:L/MVI:N/MVA:H/MSC:N/MSI:N/MSA:X	1.4	1.5
CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:L/VI:H/VA:N/SC:H/SI:N/SA:H/E:P/CR:X/IR:X/AR:M/MAV:P/MAC:H/MAT:N/MPR:H/MUI:P/MVC:X/MVI:H/MVA:L/MSC:H/MSI:H/MSA:X	4.5	4.6

**Comment by akshatvaid** [comment]
https://github.com/RedHatProductSecurity/cvss-v4-calculator/commit/266c4f6fb736378f74f748320d8cbab254ab70f1 is the commit for https://github.com/RedHatProductSecurity/cvss-v4-calculator/pull/49 which is the rounding error.

This commit corrects the rounding error. To do this, `return value.toFixed(1) ` is changed to `return Math.round(value*10)/1`0
The same change is reflected in the API https://github.com/akshatvaid/cvss-v4-node-api/blob/b57ae4655dfc0824349b3cfa081595c2313431a6/cvss-v4-calculator/cvss_score.js#L242

On digging deeper, it seems like the https://github.com/FIRSTdotorg/cvss-v4-calculator/tree/main doesn have the latest "main" from https://github.com/RedHatProductSecurity/cvss-v4-calculator. The rounding issue is current present on the authoritative first.org version of the calculator. Same can be found here: https://github.com/FIRSTdotorg/cvss-v4-calculator/blob/47726502db9610844c69d756d50cc75ec98e0c73/app.js#L522

Scores form the "main" https://github.com/RedHatProductSecurity/cvss-v4-calculator version match the API scores for all the corner cases listed in the google sheet (tested a sample of 10-15 vectors)

**Comment by akshatvaid** [comment]
Closing based on above explanation
